name: Unity RequestActivationFile

on: 
  workflow_dispatch:
    inputs:
      unity-version:
        description: 'What unityci container to use. Just need part after `ubuntu-`'     
        required: true
        default: '2021.3.30f1-base-3.0.0'
      license-file:
        description: 'Name of generated file, version expect -base...'     
        required: true
        default: '2021.3.30f1'
  
jobs:
  requestActivationFile:
    runs-on: ubuntu-latest
    container: unityci/editor:ubuntu-${{ github.event.inputs.unity-version }}
    steps:
      - name: Request manual activation file
        continue-on-error: true
        run: unity-editor -logFile /dev/stdout -createManualActivationFile -quit 

      - name: Upload License Request
        uses: actions/upload-artifact@v4
        with:
            name: Manual Activation File
            path: Unity_v${{ github.event.inputs.license-file }}.alf

      - name: Next Steps
        run: |
          echo "Upload the file to https://license.unity3d.com/manual to get a license"
          echo "Then save the license in a secret called UNITY_LICENSE"

